---
title: "p8105_hw6_co2554"
author: "Camille Okonkwo"
output: github_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(broom)
library(viridis)
library(p8105.datasets)

knitr::opts_chunk$set(
  echo = TRUE, 
  warning = FALSE,
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
  )

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Set seed for reproducibility.

```{r}
set.seed(12345)
```


###  Problem 1


### Problem 2

Downloading the Central Park weather data

```{r weather}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

We'll be looking at the distributions of these two quantities estimated from the weather_df data: r^2 and log(β̂ 1∗β̂ 2). 

Lets create a simple linear regression with `tmax` as the response and  `tmin` and `prcp` as predictors. 
```{r model}
model = lm(tmax ~ tmin + prcp, data = weather_df)

r_squared =
  model |> 
  broom::glance() |> 
  select(r.squared)

coefficients =
  model |> 
  broom::tidy() |>
  filter(term %in% c("tmin", "prcp")) |>
  select(term, estimate) |>
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) |> 
  mutate(
    log_coefficient = log(tmin * prcp)
    )

```


